# configs/baseline.yaml
experiment:
  name: "resnet18_adam_cos" 
  seed: 42
  device: "cuda:0"

data:
  dataset: "CIFAR10"
  root: "./data"
  batch_size:
    train: 128
    test: 100
  num_workers: 2
  train_transform:
    RandomCrop:
      size: 32
      padding: 4
    RandomHorizontalFlip: true
    RandomRotation: 15
    ColorJitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    RandomAffine:
      degrees: 0
      translate: [0.1, 0.1]
      scale: [0.9, 1.1]
    Normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
    RandomErasing:
      p: 0.2
      scale: [0.02, 0.2]
  test_transform:
    Normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

model:
  type: "ResNet18"
  params:
    block_type: "ResidualBlock"
    num_blocks: [2, 2, 2, 2]
    num_classes: 10

training:
  epochs: 2
  criterion: "CrossEntropyLoss"
  optimizer:
    type: "Adam"  # Can be: SGD, Adam, RMSprop, Adagrad
    lr: 0.1
    momentum: 0.9      # For SGD
    weight_decay: 5.0e-4
    beta1: 0.9         # For Adam
    beta2: 0.999       # For Adam
    alpha: 0.99        # For RMSprop
    eps: 1.0e-8          # For Adam/RMSprop
  lr_scheduler:
    type: "CosineAnnealingLR"  # Can be: CosineAnnealingLR, StepLR, ReduceLROnPlateau
    T_max: 100                 # For CosineAnnealingLR
    step_size: 30              # For StepLR
    gamma: 0.1                 # For StepLR/ReduceLROnPlateau
    patience: 7               # For ReduceLROnPlateau
    factor: 0.1                # For ReduceLROnPlateau
    threshold: 1.0e-4            # For ReduceLROnPlateau
    min_lr: 1.0e-6               # For ReduceLROnPlateau

logging:
  save_dir: "./runs"
  save_interval: 50
  visualize: true



# python scripts/train.py --config configs\resnet18_Adam.yaml
# python scripts/visualize.py --config configs/baseline.yaml --checkpoint runs/baseline_20231115/checkpoint.pth
# tensorboard --logdir=<directory_name>
